### ISSUE TITLE
"TypeError: Path segment must be bytes, but 'deluge' is <class 'str'>"

### ISSUE THREAD

**Issue by btowntkd** [linuxserver/docker-deluge#171]
After updating to the latest image last night, I started getting this error messaage on startup:
```
18:56:42 [INFO    ][deluge.configmanager:49  ] Setting config directory to: /config
18:56:42 [INFO    ][deluge.ui.ui:68  ] Deluge ui 2.1.1
18:56:42 [INFO    ][deluge.ui.ui:70  ] Starting web ui..
Traceback (most recent call last):
  File "/usr/bin/deluge-web", line 8, in <module>
    sys.exit(start())
  File "/usr/lib/python3.10/site-packages/deluge/ui/web/__init__.py", line 6, in start
    web.start()
  File "/usr/lib/python3.10/site-packages/deluge/ui/web/web.py", line 71, in start
    self.__server = server.DelugeWeb(options=self.options)
  File "/usr/lib/python3.10/site-packages/deluge/ui/web/server.py", line 685, in __init__
    self.top_level.putChild(self.base.strip('/'), self.top_level)
  File "/usr/lib/python3.10/site-packages/twisted/web/resource.py", line 234, in putChild
    raise TypeError(f"Path segment must be bytes, but {path!r} is {type(path)}")
TypeError: Path segment must be bytes, but 'deluge' is <class 'str'>
```

**Comment by lpenz** [comment]
Was able to work around it by changing /usr/lib/python3.11/site-packages/deluge/ui/web/server.py line 685 to
`self.top_level.putChild(bytes(self.base.strip('/'), 'ascii'), self.top_level)`

**Comment by btowntkd** [comment]
The fix is apparently implemented in deluge develop branch: https://git.deluge-torrent.org/deluge/commit/?h=develop&id=3565a9a817a205de912bd682b5f91428856f9607

How do we get this pulled into the docker image?

**Comment by lpenz** [comment]
Just updated, still happening

**Comment by drizuid** [comment]
We build based on what is available in the alpine edge repo. If a version is not available in that repo, it will not be in our container. The best way at this time is to follow the work-around guidance provided in https://github.com/linuxserver/docker-deluge/issues/171#issuecomment-1349910566 until the updated version is available in alpine's repo (likely sometime after deluge makes it an official release)
