### ISSUE TITLE
[BUG] RPC Error Message "RPCRequest: core.get_free_space(/downloads/Incomplete)"

### ISSUE THREAD

**Issue by instantdreams** [linuxserver/docker-deluge#176]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When running Deluge, the following error repeats inside the Deluge container logs:
```
--------------------------------------------------------------------------------
11:27:46 [ERROR   ][deluge.ui.client           :169 ] RPCError Message Received!
--------------------------------------------------------------------------------
RPCRequest: core.get_free_space(/downloads/Incomplete)
--------------------------------------------------------------------------------
OSError
[Errno 9] Bad file descriptor: b'/downloads/Incomplete': Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/deluge/core/rpcserver.py", line 326, in dispatch
    ret = self.factory.methods[method](*args, **kwargs)
  File "/usr/lib/python3/dist-packages/deluge/core/core.py", line 1257, in get_free_space
    return deluge.common.free_space(path)
  File "/usr/lib/python3/dist-packages/deluge/common.py", line 902, in free_space
    disk_data = os.statvfs(path.encode('utf8'))
OSError: [Errno 9] Bad file descriptor: b'/downloads/Incomplete'

--------------------------------------------------------------------------------
```

### Expected Behavior

Deluge should be able to access /downloads/Incomplete and /downloads/Complete

### Steps To Reproduce

1. Check folders `/media/Downloads`, `/media/Downloads/Incomplete`, & `/media/Downloads/Complete` exist and are owned by uid 1000 and gid 1000
2. Confirm nordlynx docker-compose.yml is correct
3. Confirm nordlynx .env is correct
4. Issue command `docker-compose --file /srv/nordlynx/docker-compose.yml up --detach`
5. Issue command `docker-compose --file /srv/nordlynx/docker-compose.yml logs` and confirm vpn is running
6. Confirm deluge docker-compose.yml is correct
7. Confirm deluge .env is correct
8. Issue command `docker-compose --file /srv/deluge/docker-compose.yml up --detach`
9. Issue command `docker-compose --file /srv/deluge/docker-compose.yml logs` and confirm torrent client is running
10. Attempt to connect to http://[ip.add.re.ss]:8112 to check status and configure client

### Environment

```markdown
- OS:$ Linux 5.18.0-1-amd64 #1 SMP PREEMPT_DYNAMIC Debian 5.18.2-1 (2022-06-06) x86_64 GNU/Linux

- How OS was installed:
1. Bare metal installation of Debian OS
2. Service user created and granted access to sudo users
3. Network interface configured and static IP set
4. Network packaged samba and cifs installed
5. Network shares configured
5.1. Mount targets created:
    sudo mkdir /media/Downloads/
5.2. Ownership for each mount point set:
    sudo chown 1000:1000 /media/Downloads
5.3. Create credential file for file server:
    sudo touch /root/.smbcredentials_svr-files
    sudo chmod 600 /root/.smbcredentials_svr-files
    sudo nano /root/.smbcredentials_svr-files
5.4. Populate filserver credential file:
    username=[username]
    password=[password]
    domain=workgroup
5.5. Add mount entry to /etc/fstab:
    # Windows CIFS shares
    //[ip.add.re.ss]/Downloads/        /media/Downloads/     cifs  uid=1000,gid=1000,credentials=/root/.smbcredentials_svr-files,rw,iocharset=utf8,noperm  0  0
5.6. Mount and check the shares:
    sudo mount -a
    ls -la /media
    df -H

- How docker service was installed: [Install Docker Engine on Debian](https://docs.docker.com/engine/install/debian/)
- docker version: Client: Docker Engine - Community 20.10.17
- docker version: Engine: Docker Engine - Community 20.10.17
- docker-compose version: version 1.29.2, build 5becea4c

Notes:
I have reviewed and confirmed that the permissions are correct, and believe I am following best practices for ownership of file shares. This worked previously but has started throwing errors in the last two weeks.

I raised this issue on Discord and was pointed in the direction of reviewing the way my network shares were configured. I've redone them and confirmed they are working - in fact, I am currently running the "linuxserver/transmission:latest" container with the same network shares and everything is going smoothly.
```

### CPU architecture

x86-64

### Docker creation

```bash
### user details

$ whoami
svcuser
$ id $user
uid=1000(svcuser) gid=1000(svcuser) groups=1000(svcuser),24(cdrom),25(floppy),27(sudo),29(audio),30(dip),44(video),46(plugdev),108(netdev),998(docker)
```

### nordlynx container
```
$ docker-compose --file /srv/nordlynx/docker-compose.yml config
networks:
  nordlynx_net:
    driver: bridge
    name: nordlynx_net
services:
  nordlynx:
    cap_add:
    - NET_ADMIN
    - SYS_MODULE
    container_name: nordlynx
    environment:
      NET_LOCAL: [local cidr]
      PRIVATE_KEY: [key]
      QUERY: [filters]
    healthcheck:
      test:
      - CMD-SHELL
      - curl https://api.nordvpn.com/vpn/check/full | grep '"status":"Protected"'
        && exit 0 || exit 1
    image: ghcr.io/bubuntux/nordlynx
    networks:
      nordlynx_net: null
    ports:
    - published: 8112
      target: 8112
    - published: 6881
      target: 6881
    - protocol: udp
      published: 6881
      target: 6881
    restart: unless-stopped
    sysctls:
      net.ipv4.conf.all.rp_filter: '2'
      net.ipv6.conf.all.disable_ipv6: '1'
version: '3'
```

### deluge container
```
$ docker-compose --file /srv/deluge/docker-compose.yml config
services:
  deluge:
    container_name: deluge
    environment:
      DELUGE_LOGLEVEL: info
      PGID: '1000'
      PUID: '1000'
      TZ: America/Edmonton
    image: lscr.io/linuxserver/deluge:latest
    network_mode: container:nordlynx
    restart: unless-stopped
    volumes:
    - /srv/deluge/config:/config:rw
    - /media/Downloads:/downloads:rw
version: '2.1'
```

### Container logs

```bash
### docker logs deluge

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 01-migrations: executing...
[migrations] started
[migrations] no migrations found
[cont-init.d] 01-migrations: exited 0.
[cont-init.d] 02-tamper-check: executing...
[cont-init.d] 02-tamper-check: exited 0.
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
[cont-init.d] 30-config: exited 0.
[cont-init.d] 90-custom-folders: executing...
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-scripts: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
13:10:35 [INFO    ][deluge.configmanager:52  ] Setting config directory to: /config
13:10:35 [INFO    ][deluge.ui.ui:70  ] Deluge ui 2.0.5
13:10:35 [INFO    ][deluge.ui.ui:72  ] Starting web ui..
13:10:36 [INFO    ][deluge.i18n.util           :105 ] Setting up translations from /usr/lib/python3/dist-packages/deluge/i18n
13:10:36 [INFO    ][deluge.ui.web.server       :735 ] Starting webui server at PID 325
13:10:36 [INFO    ][deluge.ui.web.server       :750 ] Serving at http://0.0.0.0:8112/
```

### cat /srv/deluge/config/deluge.pid
```
13:10:35 [INFO    ][deluge.configmanager:52  ] Setting config directory to: /config
13:10:35 [INFO    ][deluge.core.daemon            :94  ] Deluge daemon 2.0.5
13:10:35 [INFO    ][deluge.core.core              :339 ] Successfully loaded session.state: /config/session.state
13:10:35 [WARNING ][deluge.core.core              :337 ] Unable to load /config/session.state.bak: [Errno 2] No such file or directory: '/config/session.state.bak'
13:10:35 [INFO    ][deluge.core.alertmanager      :148 ] Alert Queue Size set to 10000
13:10:36 [INFO    ][deluge.core.rpcserver         :402 ] Starting DelugeRPC server :58846
13:10:36 [INFO    ][deluge.core.daemon            :154 ] Deluge daemon starting...
13:10:36 [WARNING ][deluge.core.preferencesmanager:473 ] Unable to find GeoIP database file: /usr/share/GeoIP/GeoIP.dat
13:10:36 [INFO    ][deluge_label.core             :78  ] *** Start Label plugin ***
13:10:36 [INFO    ][deluge.pluginmanagerbase      :191 ] Plugin Label enabled...
13:10:36 [INFO    ][deluge.core.authmanager       :228 ] Opening auth for load: /config/auth
13:10:36 [INFO    ][deluge.core.authmanager       :236 ] Successfully loaded auth: /config/auth
13:10:36 [INFO    ][deluge.core.torrentmanager    :818 ] Loading torrent state: /config/state/torrents.state
13:10:36 [INFO    ][deluge.core.torrentmanager    :834 ] Successfully loaded /config/state/torrents.state
13:10:36 [INFO    ][deluge.core.torrentmanager    :1081] Opening torrents.fastresume for load: /config/state/torrents.fastresume
13:10:36 [INFO    ][deluge.core.torrentmanager    :1081] Opening torrents.fastresume for load: /config/state/torrents.fastresume.bak
13:10:36 [INFO    ][deluge.core.torrentmanager    :1081] Opening torrents.fastresume for load: /config/torrents.fastresume
13:10:36 [INFO    ][deluge.core.torrentmanager    :897 ] Finished loading 0 torrents in 0:00:00.005132
13:10:37 [INFO    ][deluge.core.torrentmanager    :1630] on_alert_external_ip: 176.100.43.63
13:11:07 [INFO    ][deluge.core.rpcserver         :171 ] Deluge Client connection made from: 127.0.0.1:56944
13:11:07 [INFO    ][deluge.core.rpcserver         :171 ] Deluge Client connection made from: 127.0.0.1:56960
13:11:07 [INFO    ][deluge.core.rpcserver         :197 ] Deluge client disconnected: Connection to the other side was lost in a non-clean fashion: Connection lost.
13:11:07 [INFO    ][deluge.core.rpcserver         :197 ] Deluge client disconnected: Connection to the other side was lost in a non-clean fashion: Connection lost.
13:11:08 [INFO    ][deluge.core.rpcserver         :171 ] Deluge Client connection made from: 127.0.0.1:56964
13:11:08 [INFO    ][deluge.core.rpcserver         :197 ] Deluge client disconnected: Connection to the other side was lost in a non-clean fashion: Connection lost.
13:11:10 [INFO    ][deluge.core.rpcserver         :171 ] Deluge Client connection made from: 127.0.0.1:56970
13:11:10 [WARNING ][deluge.core.rpcserver         :238 ] An exception occurred while sending RPC_ERROR to client. Wrapping it and resending. Error to send(causing exception goes next):
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/deluge/core/rpcserver.py", line 326, in dispatch
    ret = self.factory.methods[method](*args, **kwargs)
  File "/usr/lib/python3/dist-packages/deluge/core/core.py", line 1257, in get_free_space
    return deluge.common.free_space(path)
  File "/usr/lib/python3/dist-packages/deluge/common.py", line 902, in free_space
    disk_data = os.statvfs(path.encode('utf8'))
OSError: [Errno 9] Bad file descriptor: b'/downloads/Incomplete'

13:11:10 [ERROR   ][deluge.core.rpcserver         :1481] Exception calling RPC request: [Errno 9] Bad file descriptor: b'/downloads/Incomplete'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/deluge/core/rpcserver.py", line 326, in dispatch
    ret = self.factory.methods[method](*args, **kwargs)
  File "/usr/lib/python3/dist-packages/deluge/core/core.py", line 1257, in get_free_space
    return deluge.common.free_space(path)
  File "/usr/lib/python3/dist-packages/deluge/common.py", line 902, in free_space
    disk_data = os.statvfs(path.encode('utf8'))
OSError: [Errno 9] Bad file descriptor: b'/downloads/Incomplete'
13:11:10 [WARNING ][deluge.core.rpcserver         :238 ] An exception occurred while sending RPC_ERROR to client. Wrapping it and resending. Error to send(causing exception goes next):
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/deluge/core/rpcserver.py", line 326, in dispatch
    ret = self.factory.methods[method](*args, **kwargs)
  File "/usr/lib/python3/dist-packages/deluge/core/core.py", line 1257, in get_free_space
    return deluge.common.free_space(path)
  File "/usr/lib/python3/dist-packages/deluge/common.py", line 902, in free_space
    disk_data = os.statvfs(path.encode('utf8'))
OSError: [Errno 9] Bad file descriptor: b'/downloads/Incomplete'
```

Note that this error repeats until the container is taken down.
```

**Comment by j0nnymoe** [comment]
Random thought, does it work when you disable the check free space option in deluge?

**Comment by instantdreams** [comment]
Apologies - I grabbed the wrong log files from testing.
```
$ docker inspect --format='{{.Config.Image}}' deluge
lscr.io/linuxserver/deluge:latest
```
Now running latest version

Here are the init logs:
```
$ docker logs deluge
[custom-init] No custom services found, skipping...
[migrations] started
[migrations] no migrations found

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[custom-init] No custom files found, skipping...
16:08:22 [INFO    ][deluge.configmanager:49  ] Setting config directory to: /config
16:08:23 [INFO    ][deluge.core.daemon            :1622] Deluge daemon 2.1.1
16:08:23 [WARNING ][deluge.core.core              :1622] Unable to load /config/session.state: [Errno 2] No such file or directory: '/config/session.state'
16:08:23 [WARNING ][deluge.core.core              :1622] Unable to load /config/session.state.bak: [Errno 2] No such file or directory: '/config/session.state.bak'
16:08:23 [INFO    ][deluge.core.alertmanager      :1622] Alert Queue Size set to 10000
16:08:23 [INFO    ][deluge.core.rpcserver         :1622] Starting DelugeRPC server localhost:58846
16:08:24 [INFO    ][deluge.core.daemon            :1622] Deluge daemon starting...
16:08:24 [WARNING ][deluge.core.preferencesmanager:1622] Unable to find GeoIP database file: /usr/share/GeoIP/GeoIP.dat
16:08:24 [INFO    ][deluge.core.authmanager       :1622] Opening auth for load: /config/auth
16:08:24 [INFO    ][deluge.core.authmanager       :1622] Successfully loaded auth: /config/auth
16:08:24 [INFO    ][deluge.core.torrentmanager    :1622] on_alert_external_ip: 176.100.43.63
16:08:24 [INFO    ][deluge.core.torrentmanager    :1622] Loading torrent state: /config/state/torrents.state
16:08:24 [INFO    ][deluge.core.torrentmanager    :1622] Loading torrent state: /config/state/torrents.state.bak
16:08:24 [INFO    ][deluge.core.torrentmanager    :1622] Opening torrents.fastresume for load: /config/state/torrents.fastresume
16:08:24 [INFO    ][deluge.core.torrentmanager    :1622] Opening torrents.fastresume for load: /config/state/torrents.fastresume.bak
16:08:24 [INFO    ][deluge.core.torrentmanager    :1622] Opening torrents.fastresume for load: /config/torrents.fastresume
16:08:24 [INFO    ][deluge.core.torrentmanager    :1622] Finished loading 0 torrents in 0:00:00.000399
16:08:25 [INFO    ][deluge.core.rpcserver         :1622] Deluge Client connection made from: 127.0.0.1:33557
16:08:25 [INFO    ][deluge.core.rpcserver         :1622] Deluge client disconnected: Connection to the other side was lost in a non-clean fashion: Connection lost.
16:08:25 [INFO    ][deluge.core.torrentmanager    :1622] on_alert_external_ip: 176.100.43.63
16:08:26 [INFO    ][deluge.configmanager:49  ] Setting config directory to: /config
16:08:26 [INFO    ][deluge.ui.ui:68  ] Deluge ui 2.1.1
16:08:26 [INFO    ][deluge.ui.ui:70  ] Starting web ui..
16:08:27 [WARNING ][deluge.config              :400 ] Unable to open config file /config/web.conf: [Errno 2] No such file or directory: '/config/web.conf'
16:08:27 [INFO    ][deluge.i18n.util           :101 ] Setting up translations from /usr/lib/python3.11/site-packages/deluge/i18n
16:08:27 [WARNING ][deluge.config              :400 ] Unable to open config file /config/hostlist.conf: [Errno 2] No such file or directory: '/config/hostlist.conf'
16:08:27 [WARNING ][deluge.config              :477 ] Unable to open config file: /config/hostlist.conf because: [Errno 2] No such file or directory: '/config/hostlist.conf'
16:08:27 [WARNING ][deluge.config              :502 ] Unable to backup old config: [Errno 2] No such file or directory: '/config/hostlist.conf'
16:08:27 [INFO    ][deluge.ui.web.server       :1622] Starting webui server at PID 160
16:08:27 [INFO    ][deluge.ui.web.server       :1622] Serving at http://0.0.0.0:8112/
[ls.io-init] done.
```

After initial configuration, the following errors appeared:
```
16:10:28 [WARNING ][deluge.core.rpcserver         :1622] An exception occurred while sending RPC_ERROR to client. Wrapping it and resending. Error to send(causing exception goes next):
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/deluge/core/rpcserver.py", line 334, in dispatch
    ret = self.factory.methods[method](*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/deluge/core/core.py", line 1243, in get_free_space
    return deluge.common.free_space(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/deluge/common.py", line 905, in free_space
    disk_data = os.statvfs(path.encode('utf8'))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 9] Bad file descriptor: b'/downloads'

16:10:28 [ERROR   ][deluge.core.rpcserver         :1622] Exception calling RPC request: [Errno 9] Bad file descriptor: b'/downloads'
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/deluge/core/rpcserver.py", line 334, in dispatch
    ret = self.factory.methods[method](*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/deluge/core/core.py", line 1243, in get_free_space
    return deluge.common.free_space(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/deluge/common.py", line 905, in free_space
    disk_data = os.statvfs(path.encode('utf8'))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 9] Bad file descriptor: b'/downloads'
16:10:28 [ERROR   ][deluge.ui.client           :1622] RPCError Message Received!
--------------------------------------------------------------------------------
RPCRequest: core.get_free_space(/downloads)
--------------------------------------------------------------------------------
OSError
[Errno 9] Bad file descriptor: b'/downloads': Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/deluge/core/rpcserver.py", line 334, in dispatch
    ret = self.factory.methods[method](*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/deluge/core/core.py", line 1243, in get_free_space
    return deluge.common.free_space(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/deluge/common.py", line 905, in free_space
    disk_data = os.statvfs(path.encode('utf8'))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 9] Bad file descriptor: b'/downloads'

--------------------------------------------------------------------------------
16:10:35 [WARNING ][deluge.config              :477 ] Unable to open config file: /config/web.conf because: [Errno 2] No such file or directory: '/config/web.conf'
16:10:35 [WARNING ][deluge.config              :502 ] Unable to backup old config: [Errno 2] No such file or directory: '/config/web.conf'
16:11:24 [INFO    ][deluge_label.core             :1622] *** Start Label plugin ***
16:11:24 [WARNING ][deluge.config                 :400 ] Unable to open config file /config/label.conf: [Errno 2] No such file or directory: '/config/label.conf'
16:11:24 [INFO    ][deluge.pluginmanagerbase      :1622] Plugin Label enabled...
16:11:24 [INFO    ][deluge.pluginmanagerbase   :1622] Plugin Label enabled...
16:11:30 [WARNING ][deluge.config                 :477 ] Unable to open config file: /config/label.conf because: [Errno 2] No such file or directory: '/config/label.conf'
16:11:30 [WARNING ][deluge.config                 :502 ] Unable to backup old config: [Errno 2] No such file or directory: '/config/label.conf'
```
You can see in the logs where the error occurred before I finished the configuration including label plug in set up.

 "Pre-allocate disk space" is unchecked and has been always.

**Comment by instantdreams** [comment]
Also just to confirm that the container also sees the downloads location correctly.

View from host:
```
$ ls -la /media/Downloads/
total 4
drwxr-xr-x  2 idsvc idsvc    0 Oct 25 13:42 .
drwxr-xr-x 15 idsvc idsvc 4096 Jun 14 17:55 ..
drwxr-xr-x  2 idsvc idsvc    0 Nov 30 10:50 Complete
drwxr-xr-x  2 idsvc idsvc    0 Nov 30 14:57 Incomplete
```

View from container:
```
$ docker exec -it -u abc deluge bash
bash: /root/.bashrc: Permission denied
abc@456d91bf2949:/$ ls -la downloads/
total 4
drwxr-xr-x 2 abc  users    0 Oct 25 13:42 .
drwxr-xr-x 1 root root  4096 Nov 30 16:08 ..
drwxr-xr-x 2 abc  users    0 Nov 30 10:50 Complete
drwxr-xr-x 2 abc  users    0 Nov 30 14:57 Incomplete
```

**Comment by instantdreams** [comment]
I reviewed this issue again.

The `Bad file descriptor` error message related to the way the CIFS share has been mounted. To resolve this, the file system table was updated to harden the connection:
```
//192.168.1.194/Downloads/        /media/Downloads/     cifs  uid=1000,gid=1000,credentials=/root/.smbcredentials,rw,iocharset=utf8,vers=3.1.1,mfsymlinks,nosetuids,noperm  0  0
```

With this complete and the server rebooted, the connection has been stable again.
