### ISSUE TITLE
[BUG] `TypeError: Path segment must be bytes, but 'deluge' is <class 'str'>` on startup

### ISSUE THREAD

**Issue by lpenz** [linuxserver/docker-deluge#177]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This shows up on startup:
```
Traceback (most recent call last):
  File "/usr/bin/deluge-web", line 8, in <module>
    sys.exit(start())
  File "/usr/lib/python3.10/site-packages/deluge/ui/web/__init__.py", line 6, in start
    web.start()
  File "/usr/lib/python3.10/site-packages/deluge/ui/web/web.py", line 71, in start
    self.__server = server.DelugeWeb(options=self.options)
  File "/usr/lib/python3.10/site-packages/deluge/ui/web/server.py", line 685, in __init__
    self.top_level.putChild(self.base.strip('/'), self.top_level)
  File "/usr/lib/python3.10/site-packages/twisted/web/resource.py", line 234, in putChild
    raise TypeError(f"Path segment must be bytes, but {path!r} is {type(path)}")
TypeError: Path segment must be bytes, but 'deluge' is <class 'str'>
```
And then the container is not started.

### Steps To Reproduce

1. Start the container

### Environment

```markdown
- OS: Debian on Rapsberry PI
- How docker service was installed: distro's
```

### CPU architecture

arm64

### Docker creation

```bash
/usr/bin/docker run --rm \
                    --name=deluge \
                    --network=host \
                    -v /config/deluge:/config \
                    -v /incoming:/incoming -v /in:/downloads \
                    -e PGID=1000 -e PUID=1000  \
                    -p 8112:8112 \
                    linuxserver/deluge
```

### Container logs

```bash
Traceback (most recent call last):
  File "/usr/bin/deluge-web", line 8, in <module>
    sys.exit(start())
             ^^^^^^^
  File "/usr/lib/python3.11/site-packages/deluge/ui/web/__init__.py", line 6, in start
    web.start()
  File "/usr/lib/python3.11/site-packages/deluge/ui/web/web.py", line 71, in start
    self.__server = server.DelugeWeb(options=self.options)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/deluge/ui/web/server.py", line 685, in __init__
    self.top_level.putChild(self.base.strip('/'), self.top_level)
  File "/usr/lib/python3.11/site-packages/twisted/web/resource.py", line 234, in putChild
    raise TypeError(f"Path segment must be bytes, but {path!r} is {type(path)}")
TypeError: Path segment must be bytes, but 'deluge' is <class 'str'>
```

**Comment by lpenz** [comment]
Found it: https://github.com/linuxserver/docker-deluge/issues/171
