### ISSUE TITLE
[BUG] deluge container dropping webui connection, hogging CPU

### ISSUE THREAD

**Issue by aaronmgriffin** [linuxserver/docker-deluge#210]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm sorry I do not have any more details, but within the past few releases, deluge began to exhibit strange behavior.

1. The webui periodically drops the connection, opening the connection manager dialog. Previous to ~1 month ago, I would keep a deluge tab open for weeks on end. Now it drops connection multiple times per day
2. On occasion, possible when the webui disconnects, the deluge docker container appears to be wildly thrashing the CPU. There are no relevant container logs.

### Steps To Reproduce

Running :latest

### Environment

```markdown
- OS: Linux 6.11.9-arch1-1
- How docker service was installed: pacman
```

### CPU architecture

x86-64

### Docker creation

```bash
x-lsio-common: &lsio_common
  restart: unless-stopped
  network_mode: service:gluetun
  depends_on:
    - gluetun
  environment:
    - PUID=1000
    - PGID=100
    - TZ=America/Chicago
    - AUTO_UPDATE=true
    - UMASK_SET=022

...

  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    environment:
      - DELUGE_LOGLEVEL=error
      - WEBUI_PORT=8080
    volumes:
      - ./config/deluge:/config
      - ./downloads:/downloads
    <<: *lsio_common
```
```


### Container logs

```bash
To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    911
User GID:    911
───────────────────────────────────────
Linuxserver.io version: 2.1.1-r10-ls303
Build-date: 2024-12-16T15:46:32+00:00
───────────────────────────────────────
    
[custom-init] No custom files found, skipping...
Connection to 127.0.0.1 58846 port [tcp/*] succeeded!
```
```

**Comment by aaronmgriffin** [comment]
After a reboot, I see this in the logs right about the time the webui dropped
```
deluge    | Unhandled Error
deluge    | Traceback (most recent call last):
deluge    |   File "/usr/lib/python3.12/site-packages/deluge/core/daemon_entry.py", line 119, in run_daemon
deluge    |     daemon.start()
deluge    |   File "/usr/lib/python3.12/site-packages/deluge/core/daemon.py", line 161, in start
deluge    |     reactor.run()
deluge    |   File "/usr/lib/python3.12/site-packages/twisted/internet/base.py", line 1318, in run
deluge    |     self.mainLoop()
deluge    |   File "/usr/lib/python3.12/site-packages/twisted/internet/base.py", line 1328, in mainLoop
deluge    |     reactorBaseSelf.runUntilCurrent()
deluge    | --- <exception caught here> ---
deluge    |   File "/usr/lib/python3.12/site-packages/twisted/internet/base.py", line 994, in runUntilCurrent
deluge    |     call.func(*call.args, **call.kw)
deluge    |   File "/usr/lib/python3.12/site-packages/deluge/core/torrentmanager.py", line 1389, in on_alert_tracker_error
deluge    |     error_message = decode_bytes(alert.error_message())
deluge    | Boost.Python.ArgumentError: Python argument types in
deluge    |     tracker_error_alert.error_message(tracker_error_alert)
deluge    | did not match C++ signature:
deluge    |     error_message(libtorrent::tracker_error_alert {lvalue})
deluge    | 
deluge    | Connection to 127.0.0.1 58846 port [tcp/*] succeeded!
```

**Comment by eden881** [comment]
I'd use the compose file to pin the image version. Use the one that worked for you a month ago. I don't think there's a point upgrading it, Deluge itself is rarely updated.

**Comment by moto-ctrl** [comment]
I'm not seeing this behaviour, I've just also updated to the latest image. But I use rpi so it's ARM64
I'll update this issue if I see anything not working properly on my setup.
