### ISSUE TITLE
Error on start when running through VPN

### ISSUE THREAD

**Issue by stramel** [linuxserver/docker-deluge#24]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

OS: Ubuntu 15.10

You can see my docker-compose file here : https://github.com/stramel/htpc/blob/master/docker-compose.yml
Running deluge through a VPN container and it either does one of the two snippets...

```
*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/my_init.d/10_add_user_abc.sh...

-------------------------------------
          _     _ _
         | |___| (_) ___
         | / __| | |/ _ \
         | \__ \ | | (_) |
         |_|___/ |_|\___/
               |_|

Brought to you by linuxserver.io
We do accept donations at:
https://www.linuxserver.io/donations
-------------------------------------
GID/UID
-------------------------------------
User uid:    1050
User gid:    1050
-------------------------------------

*** Running /etc/my_init.d/20_apt_update.sh...
finding fastest mirror
Getting list of mirrors...Traceback (most recent call last):
  File "/usr/lib/python3.4/urllib/request.py", line 1182, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.4/http/client.py", line 1088, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.4/http/client.py", line 1126, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.4/http/client.py", line 1084, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.4/http/client.py", line 922, in _send_output
    self.send(msg)
  File "/usr/lib/python3.4/http/client.py", line 857, in send
    self.connect()
  File "/usr/lib/python3.4/http/client.py", line 834, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python3.4/socket.py", line 494, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.4/socket.py", line 533, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/aptselect/util_funcs.py", line 19, in get_html
    html = urlopen(url)
  File "/usr/lib/python3.4/urllib/request.py", line 161, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 463, in open
    response = self._open(req, data)
  File "/usr/lib/python3.4/urllib/request.py", line 481, in _open
    '_open', req)
  File "/usr/lib/python3.4/urllib/request.py", line 441, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 1210, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.4/urllib/request.py", line 1184, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/aptselect/apt-select.py", line 179, in apt_select
    mirrors_list = get_html(mirrors_url)
  File "/app/aptselect/util_funcs.py", line 21, in get_html
    raise HTMLGetError(err)
util_funcs.HTMLGetError: <urlopen error [Errno -2] Name or service not known>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/aptselect/apt-select.py", line 341, in <module>
    apt_select()
  File "/app/aptselect/apt-select.py", line 181, in apt_select
    exit("Error getting list from %s:\n\t%s" % (mirrors_list, err))
UnboundLocalError: local variable 'mirrors_list' referenced before assignment
We are now refreshing packages from apt repositories, this *may* take a while
Err http://apt.linuxserver.io trusty InRelease

Err http://apt.linuxserver.io trusty-updates InRelease

Err http://apt.linuxserver.io trusty-security InRelease

Err http://ppa.launchpad.net trusty InRelease

Err http://apt.linuxserver.io trusty Release.gpg
  Could not resolve 'apt.linuxserver.io'
Err http://apt.linuxserver.io trusty-updates Release.gpg
  Could not resolve 'apt.linuxserver.io'
Err http://ppa.launchpad.net trusty Release.gpg
  Could not resolve 'ppa.launchpad.net'
Err http://apt.linuxserver.io trusty-security Release.gpg
  Could not resolve 'apt.linuxserver.io'
Reading package lists...
W: Failed to fetch http://apt.linuxserver.io/ubuntu/dists/trusty/InRelease

W: Failed to fetch http://apt.linuxserver.io/ubuntu/dists/trusty-updates/InRelease

W: Failed to fetch http://apt.linuxserver.io/ubuntu/dists/trusty-security/InRelease

W: Failed to fetch http://ppa.launchpad.net/deluge-team/ppa/ubuntu/dists/trusty/InRelease

W: Failed to fetch http://apt.linuxserver.io/ubuntu/dists/trusty/Release.gpg  Could not resolve 'apt.linuxserver.io'

W: Failed to fetch http://apt.linuxserver.io/ubuntu/dists/trusty-updates/Release.gpg  Could not resolve 'apt.linuxserver.io'

W: Failed to fetch http://apt.linuxserver.io/ubuntu/dists/trusty-security/Release.gpg  Could not resolve 'apt.linuxserver.io'

W: Failed to fetch http://ppa.launchpad.net/deluge-team/ppa/ubuntu/dists/trusty/Release.gpg  Could not resolve 'ppa.launchpad.net'

W: Some index files failed to download. They have been ignored, or old ones used instead.
*** Running /etc/my_init.d/999_advanced_script.sh...
*** Running /etc/rc.local...
*** Booting runit daemon...
*** Runit started as PID 36
[INFO    ] 23:47:30 configmanager:70 Setting config directory to: /config
[INFO    ] 23:47:30 ui:121 Deluge ui 1.3.12
[INFO    ] 23:47:30 ui:124 Starting web ui..
[INFO    ] 23:47:30 server:662 Starting server in PID 44.
[INFO    ] 23:47:30 server:676 serving on 0.0.0.0:8112 view at http://127.0.0.1:8112
Mar 12 23:47:30 1183c847cdde syslog-ng[46]: syslog-ng starting up; version='3.5.3'
```
OR

```
$ docker logs -f deluge
*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/my_init.d/10_add_user_abc.sh...

-------------------------------------
          _     _ _
         | |___| (_) ___
         | / __| | |/ _ \
         | \__ \ | | (_) |
         |_|___/ |_|\___/
               |_|

Brought to you by linuxserver.io
We do accept donations at:
https://www.linuxserver.io/donations
-------------------------------------
GID/UID
-------------------------------------
User uid:    1050
User gid:    1050
-------------------------------------

*** Running /etc/my_init.d/20_apt_update.sh...
finding fastest mirror
Getting list of mirrors...done.
Testing 77 mirror(s)
[4/77] 5%
connection to mirror.us.leaseweb.net: timed out
[5/77] 6%[Errno -3] Temporary failure in name resolution: http://mirrors.rit.edu/ubuntu/ ignored
[6/77] 7%[Errno -3] Temporary failure in name resolution: http://mirror.nodesdirect.com/ubuntu/ ignored
[7/77] 9%[Errno -3] Temporary failure in name resolution: http://ubuntuarchive.mirror.nac.net/ ignored
[8/77] 10%[Errno -3] Temporary failure in name resolution: http://mirrors.wikimedia.org/ubuntu/ ignored
[9/77] 11%[Errno -3] Temporary failure in name resolution: http://mirror.umd.edu/ubuntu/ ignored
[10/77] 12%[Errno -3] Temporary failure in name resolution: http://ubuntu.mirrors.pair.com/archive/ ignored
[11/77] 14%[Errno -3] Temporary failure in name resolution: http://mirror.atlantic.net/ubuntu/ ignored
[12/77] 15%[Errno -3] Temporary failure in name resolution: http://mirrors.mit.edu/ubuntu/ ignored
[13/77] 16%[Errno -3] Temporary failure in name resolution: http://mirrors.maine.edu/ubuntu/ ignored
[14/77] 18%[Errno -3] Temporary failure in name resolution: http://ubuntu.mirrors.tds.net/pub/ubuntu/ ignored
[15/77] 19%[Errno -3] Temporary failure in name resolution: http://mirror.imbrandon.com/ubuntu/ ignored
[16/77] 20%[Errno -3] Temporary failure in name resolution: http://archive.ubuntu.com/ubuntu/ ignored
[17/77] 22%[Errno -3] Temporary failure in name resolution: http://ftp.usf.edu/pub/ubuntu/ ignored
[18/77] 23%[Errno -3] Temporary failure in name resolution: http://ubuntu.mirrors.wvstateu.edu/ ignored
[19/77] 24%[Errno -3] Temporary failure in name resolution: http://cosmos.cites.illinois.edu/pub/ubuntu/ ignored
[20/77] 25%[Errno -3] Temporary failure in name resolution: http://mirrors.xmission.com/ubuntu/ ignored
[21/77] 27%[Errno -3] Temporary failure in name resolution: http://mirror.steadfast.net/ubuntu/ ignored
[22/77] 28%[Errno -3] Temporary failure in name resolution: http://repos.forethought.net/ubuntu/ ignored
[23/77] 29%[Errno -3] Temporary failure in name resolution: http://mirrors.usinternet.com/ubuntu/archive/ ignored
[24/77] 31%[Errno -3] Temporary failure in name resolution: http://ubuntu.mirror.constant.com/ ignored
[25/77] 32%[Errno -3] Temporary failure in name resolution: http://mirror.hmc.edu/ubuntu/ ignored
[26/77] 33%[Errno -3] Temporary failure in name resolution: http://mirror.cs.pitt.edu/ubuntu/archive/ ignored
[27/77] 35%[Errno -3] Temporary failure in name resolution: http://mirror.ancl.hawaii.edu/linux/ubuntu/ ignored
[28/77] 36%[Errno -3] Temporary failure in name resolution: http://mirrors.us.kernel.org/ubuntu/ ignored
[29/77] 37%*** An error occurred. Aborting.
*** Shutting down /etc/my_init.d/20_apt_update.sh (PID 23)...
*** Init system aborted.
*** Killing all processes...

```

**Comment by sparklyballs** [comment]
you've got a very old version of the deluge image on your system
the apt-update script was dropped nearly a year ago

you need to delete your local image and repull

**Comment by stramel** [comment]
Bahh, shoot! Thanks! Was missing this in my update script 😅
