### ISSUE TITLE
Deluge won't start - permission denied

### ISSUE THREAD

**Issue by timsu343** [linuxserver/docker-deluge#39]
I am trying to create deluge in a docker but am running into permission denied errors and deluge cannot even start. I have checked through the github closed issues list but am still at a lost of what to do.

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

 RHEL 7.4 Developer License

As root:
docker create --name deluge_shows --net=host -p 8112:8112 -e PUID=1001 -e PGID=1003 -e TZ=America/New_York -e UMASK_SET=022 -v /root/media/Deluge/Shows:/downloads -v /deluge_config/deluge_shows:/config linuxserver/delugell

PUID and PGID of user deluge
uid=1001(deluge) gid=1003(deluge) groups=1003(deluge)

who owns the directories

drwxrwxrwx. 2 deluge deluge 6 Feb  2 18:58 deluge_shows
drwxr-xr-x. 2 deluge deluge 6 Feb  2 19:03 Shows

`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing...
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/
Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donations/
-------------------------------------
GID/UID
-------------------------------------
User uid:    1001
User gid:    1003
-------------------------------------
usermod: Failed to change ownership of the home directorychown: changing ownership of '/config': Permission denied
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
chown: cannot read directory '/config': Permission denied
chown: changing ownership of '/downloads': Permission denied
[cont-init.d] 30-config: exited 1.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Traceback (most recent call last):
  File "/usr/bin/deluged", line 11, in <module>
    load_entry_point('deluge==1.3.15', 'console_scripts', 'deluged')()
  File "/usr/lib/python2.7/site-packages/deluge/main.py", line 194, in start_daemon
    deluge.log.setupLogger(level=options.loglevel, filename=options.logfile)
  File "/usr/lib/python2.7/site-packages/deluge/log.py", line 65, in setupLogger
    filemode=filemode
  File "/usr/lib/python2.7/logging/__init__.py", line 1547, in basicConfig
    hdlr = FileHandler(filename, mode)
  File "/usr/lib/python2.7/logging/__init__.py", line 913, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python2.7/logging/__init__.py", line 943, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 13] Permission denied: '/config/deluged.log'
[INFO    ] 04:45:30 configmanager:70 Setting config directory to: /config
[INFO    ] 04:45:30 ui:124 Deluge ui 1.3.15
[INFO    ] 04:45:30 ui:127 Starting web ui..
Traceback (most recent call last):
  File "/usr/bin/deluged", line 11, in <module>
    load_entry_point('deluge==1.3.15', 'console_scripts', 'deluged')()
  File "/usr/lib/python2.7/site-packages/deluge/main.py", line 194, in start_daemon
    deluge.log.setupLogger(level=options.loglevel, filename=options.logfile)
  File "/usr/lib/python2.7/site-packages/deluge/log.py", line 65, in setupLogger
    filemode=filemode
  File "/usr/lib/python2.7/logging/__init__.py", line 1547, in basicConfig
    hdlr = FileHandler(filename, mode)
  File "/usr/lib/python2.7/logging/__init__.py", line 913, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python2.7/logging/__init__.py", line 943, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 13] Permission denied: '/config/deluged.log'
[WARNING ] 04:45:30 config:364 Unable to open config file /config/web.conf: [Errno 2] No such file or directory: '/config/web.conf'
Traceback (most recent call last):
  File "/usr/bin/deluge-web", line 11, in <module>
    load_entry_point('deluge==1.3.15', 'console_scripts', 'deluge-web')()
  File "/usr/lib/python2.7/site-packages/deluge/ui/web/web.py", line 144, in start
    web.start()
  File "/usr/lib/python2.7/site-packages/deluge/ui/web/web.py", line 111, in start
    self.__server = server.DelugeWeb()
  File "/usr/lib/python2.7/site-packages/deluge/ui/web/server.py", line 633, in __init__
    self.top_level = TopLevel()
  File "/usr/lib/python2.7/site-packages/deluge/ui/web/server.py", line 505, in __init__
    self.putChild("tracker", Tracker())
  File "/usr/lib/python2.7/site-packages/deluge/ui/web/server.py", line 208, in __init__
    self.tracker_icons = TrackerIcons()
  File "/usr/lib/python2.7/site-packages/deluge/ui/tracker_icons.py", line 161, in __init__
    os.makedirs(self.dir)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/config/icons'
[INFO    ] 04:45:31 configmanager:70 Setting config directory to: /config
[INFO    ] 04:45:31 ui:124 Deluge ui 1.3.15
[INFO    ] 04:45:31 ui:127 Starting web ui..
Traceback (most recent call last):
  File "/usr/bin/deluged", line 11, in <module>
    load_entry_point('deluge==1.3.15', 'console_scripts', 'deluged')()
  File "/usr/lib/python2.7/site-packages/deluge/main.py", line 194, in start_daemon
    deluge.log.setupLogger(level=options.loglevel, filename=options.logfile)
  File "/usr/lib/python2.7/site-packages/deluge/log.py", line 65, in setupLogger
    filemode=filemode
  File "/usr/lib/python2.7/logging/__init__.py", line 1547, in basicConfig
    hdlr = FileHandler(filename, mode)
  File "/usr/lib/python2.7/logging/__init__.py", line 913, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python2.7/logging/__init__.py", line 943, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 13] Permission denied: '/config/deluged.log'
[WARNING ] 04:45:31 config:364 Unable to open config file /config/web.conf: [Errno 2] No such file or directory: '/config/web.conf'
Traceback (most recent call last):
  File "/usr/bin/deluge-web", line 11, in <module>
    load_entry_point('deluge==1.3.15', 'console_scripts', 'deluge-web')()
  File "/usr/lib/python2.7/site-packages/deluge/ui/web/web.py", line 144, in start
    web.start()
  File "/usr/lib/python2.7/site-packages/deluge/ui/web/web.py", line 111, in start
    self.__server = server.DelugeWeb()
  File "/usr/lib/python2.7/site-packages/deluge/ui/web/server.py", line 633, in __init__
    self.top_level = TopLevel()
  File "/usr/lib/python2.7/site-packages/deluge/ui/web/server.py", line 505, in __init__
    self.putChild("tracker", Tracker())
  File "/usr/lib/python2.7/site-packages/deluge/ui/web/server.py", line 208, in __init__
    self.tracker_icons = TrackerIcons()
  File "/usr/lib/python2.7/site-packages/deluge/ui/tracker_icons.py", line 161, in __init__
    os.makedirs(self.dir)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
`

##  Thanks, team linuxserver.io

Thanks in advance for your help!

**Comment by sparklyballs** [comment]
your docker user with 1001:1000 does not have permissions on /deluge_config and /root on the host 

change permissions for /deluge_config to match the user or even better use the home folder of your user for config files

and you cannot use /root for downloads

**Comment by timsu343** [comment]
Hello,

I have changed my create command to

docker create --name deluge_shows --net=host -p 8112:8112 -e PUID=1001 -e PGID=1003 -e TZ=America/New_York -e UMASK_SET=022 -v /home/deluge/Shows:/downloads -v /home/deluge/show_config:/config linuxserver/deluge

PUID and PGID of user deluge
uid=1001(deluge) gid=1003(deluge) groups=1003(deluge)

and am still running into the same permission errors above.


[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing...
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/
Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donations/
-------------------------------------
GID/UID
-------------------------------------
User uid:    1001
User gid:    1003
-------------------------------------
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
[cont-init.d] 30-config: exited 1.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[INFO    ] 16:20:57 configmanager:70 Setting config directory to: /config
[INFO    ] 16:20:57 ui:124 Deluge ui 1.3.15
[INFO    ] 16:20:57 ui:127 Starting web ui..
[WARNING ] 16:20:58 config:364 Unable to open config file /config/web.conf: [Errno 2] No such file or directory: '/config/web.conf'
Traceback (most recent call last):
  File "/usr/bin/deluge-web", line 11, in <module>
    load_entry_point('deluge==1.3.15', 'console_scripts', 'deluge-web')()
  File "/usr/lib/python2.7/site-packages/deluge/ui/web/web.py", line 144, in start
    web.start()
  File "/usr/lib/python2.7/site-packages/deluge/ui/web/web.py", line 111, in start
    self.__server = server.DelugeWeb()
  File "/usr/lib/python2.7/site-packages/deluge/ui/web/server.py", line 633, in __init__
    self.top_level = TopLevel()
  File "/usr/lib/python2.7/site-packages/deluge/ui/web/server.py", line 505, in __init__
    self.putChild("tracker", Tracker())
  File "/usr/lib/python2.7/site-packages/deluge/ui/web/server.py", line 208, in __init__
    self.tracker_icons = TrackerIcons()
  File "/usr/lib/python2.7/site-packages/deluge/ui/tracker_icons.py", line 161, in __init__
    os.makedirs(self.dir)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/config/icons'
Traceback (most recent call last):
  File "/usr/bin/deluged", line 11, in <module>
    load_entry_point('deluge==1.3.15', 'console_scripts', 'deluged')()
  File "/usr/lib/python2.7/site-packages/deluge/main.py", line 194, in start_daemon
    deluge.log.setupLogger(level=options.loglevel, filename=options.logfile)
  File "/usr/lib/python2.7/site-packages/deluge/log.py", line 65, in setupLogger
    filemode=filemode
  File "/usr/lib/python2.7/logging/__init__.py", line 1547, in basicConfig
    hdlr = FileHandler(filename, mode)
  File "/usr/lib/python2.7/logging/__init__.py", line 913, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python2.7/logging/__init__.py", line 943, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 13] Permission denied: '/config/deluged.log'
[INFO    ] 16:20:58 configmanager:70 Setting config directory to: /config
[INFO    ] 16:20:58 ui:124 Deluge ui 1.3.15
[INFO    ] 16:20:58 ui:127 Starting web ui..
Traceback (most recent call last):
  File "/usr/bin/deluged", line 11, in <module>
    load_entry_point('deluge==1.3.15', 'console_scripts', 'deluged')()
  File "/usr/lib/python2.7/site-packages/deluge/main.py", line 194, in start_daemon
    deluge.log.setupLogger(level=options.loglevel, filename=options.logfile)
  File "/usr/lib/python2.7/site-packages/deluge/log.py", line 65, in setupLogger
    filemode=filemode
  File "/usr/lib/python2.7/logging/__init__.py", line 1547, in basicConfig
    hdlr = FileHandler(filename, mode)
  File "/usr/lib/python2.7/logging/__init__.py", line 913, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python2.7/logging/__init__.py", line 943, in _open
    stream = open(self.baseFilename, self.mode)

**Comment by timsu343** [comment]
Do i need to add web.conf and other such files in /home/deluge/show_config ?
