### ISSUE TITLE
Openssl error after newest update

### ISSUE THREAD

**Issue by MaT1g3R** [linuxserver/docker-deluge#53]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	
Host OS:

Debian 9

docker-compose.yml

```yml
  deluge:
    container_name: deluge
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Canada/Eastern
    image: linuxserver/deluge
    network_mode: host
    restart: always
    volumes:
      - /srv/nfs/Downloads:/downloads
      - /srv/nfs/appdata/deluge:/config
      - /srv/nfs:/nfs
```

Docker log output:
```python
Traceback (most recent call last):
   File "/usr/bin/deluge-web", line 11, in <module>
     load_entry_point('deluge==1.3.15', 'console_scripts', 'deluge-web')()
   File "/usr/lib/python2.7/site-packages/deluge/ui/web/web.py", line 144, in start
     web.start()
   File "/usr/lib/python2.7/site-packages/deluge/ui/web/web.py", line 110, in start
     import server
   File "/usr/lib/python2.7/site-packages/deluge/ui/web/server.py", line 50, in <module>
     from OpenSSL.crypto import FILETYPE_PEM
   File "/usr/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
     from OpenSSL import crypto, SSL
   File "/usr/lib/python2.7/site-packages/OpenSSL/crypto.py", line 16, in <module>
     from OpenSSL._util import (
   File "/usr/lib/python2.7/site-packages/OpenSSL/_util.py", line 6, in <module>
     from cryptography.hazmat.bindings.openssl.binding import Binding
   File "/usr/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 13, in <module>
     from cryptography.hazmat.bindings._openssl import ffi, lib
 ImportError: Error relocating /usr/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so: SSL_CTX_set_psk_client_callback: symbol not found
```

**Comment by lsaadeh** [comment]
same issue here

**Comment by MrTimscampi** [comment]
You can recreate your container with the image as linuxserver/deluge:145 in the meantime. It should pull the image before the latest one, which was working.

Re-update your container to linuxserver/deluge:latest once this is fixed and you should be good to go.

**Comment by lsaadeh** [comment]
Working again thanks!

**Comment by MaT1g3R** [comment]
Thanks, rolling back to 145 worked

**Comment by sm0kingm4n** [comment]
same problem here

**Comment by j0nnymoe** [comment]
@sm0kingm4n as @homerr said previous to your comment, rollback to the previous tag until further notice.

**Comment by sigboe** [comment]
Same issue in unRAID, rollback to 145 also worked.

**Comment by aptalca** [comment]
We have a new dev version rebased on ubuntu bionic. Can you guys test it and let us know if there are any issues?
Test image is at `lsiodev/deluge`

Thanks

**Comment by Lattyware** [comment]
It is obviously too late to bother now, but in future cases, it'd be a nice thing to republish `latest` to point at the last working version when something breaks like this, until a new fixed version is released - assuming that's a reasonable simple task and there is no particular reason not to. It would mean less people are affected and require less manual intervention.

**Comment by aptalca** [comment]
Latest is just that, latest. By definition it is the latest build, not the latest stable. We have versioning of our images so that if the latest build is not working, you can safely go to another build that works.

**Comment by Bothari** [comment]
Can we get a "stable" tag on Linuxserver docker images then? That would be incredibly helpful. :)

**Comment by j0nnymoe** [comment]
No - 9 times out of 10, latest is stable. We have stable branches on containers that justify it, TVHeadend for example as they run 2 branches.

**Comment by Bothari** [comment]
Hopefully it would add very little complexity to the build process. Set up stable to match latest, then in the rare occasions that latest does break an image, like this, it would be trivial to just tag the previous image as stable and fix everyone's builds.

**Comment by aptalca** [comment]
Our new build system has other checks and balances to make sure the automated builds are working prior to push so we shouldn't need to add another complexity. For instance, the new builder fires up a container based on the new build and takes a screenshot of the web gui to confirm the app comes online before pushing it to the hub. But it's new and is still being optimized. We are slowly migrating the images over. The dev build linked above is utilizing the new build system, and it is multi-arch.

Plus, something like this happens rarely and when it does, we are (in most cases) able to fix it quickly. Unfortunately this issue was a deeper one that required us to switch from alpine to ubuntu as the base, which is a very drastic change. 

I think it's ok to push. The app works, and a few plugins I tested also work. If there are issues, we'll fix them later.
