### ISSUE TITLE
something wrong with peers tab deluge v2

### ISSUE THREAD

**Issue by sparklyballs** [linuxserver/docker-deluge#66]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

##  Thanks, team linuxserver.io

hitting up the peers tab for a torrent on version 2 of deluge gives this error on a loop 

``
11:06:24 [CRITICAL][twisted                    :154 ] Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/twisted/protocols/basic.py", line 571, in dataReceived
    why = self.lineReceived(line)
  File "/usr/lib/python3/dist-packages/twisted/web/http.py", line 2013, in lineReceived
    self.allContentReceived()
  File "/usr/lib/python3/dist-packages/twisted/web/http.py", line 2104, in allContentReceived
    req.requestReceived(command, path, version)
  File "/usr/lib/python3/dist-packages/twisted/web/http.py", line 866, in requestReceived
    self.process()
--- <exception caught here> ---
  File "/usr/lib/python3/dist-packages/twisted/web/server.py", line 195, in process
    self.render(resrc)
  File "/usr/lib/python3/dist-packages/twisted/web/server.py", line 255, in render
    body = resrc.render(self)
  File "/usr/lib/python3/dist-packages/deluge/ui/web/server.py", line 205, in render
    path = ('ui', 'data', 'pixmaps', 'flags', request.country.lower() + '.png')
builtins.TypeError: can't concat str to bytes
``

locally i tried the testing repo for deluge with version 2.1x and it's the same there, so i think this is  either something upstream in the code, or a missing dependency/python version issue.

this is more for information than anything else, expect to see bajillion posts about it imminently from updating users.

**Comment by thelamer** [comment]
Upstream:

https://github.com/deluge-torrent/deluge/pull/244

**Comment by thelamer** [comment]
fixed upstream 
https://github.com/linuxserver/docker-deluge/releases/tag/2.0.3-2201906121747ubuntu18.04.1-ls26
