### ISSUE TITLE
Not a single torrent works, just magnet links

### ISSUE THREAD

**Issue by arjenanker** [linuxserver/docker-deluge#80]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior
Added torrents should work

## Current Behavior
Every single torrent I add gives an "Error: Invalid argument" error in the Tracker Status field and just sits there.

Also, the log is completely packed with these errors, every single second:
```
22:39:13 [WARNING ][deluge.core.core              :655 ] Session status key not valid: dht_cache_nodes
22:39:13 [WARNING ][deluge.core.core              :655 ] Session status key not valid: num_connections

```

## Steps to Reproduce

1. Add a torrent file to the webui. Magnets do work.

## Environment
**OS:** Ubuntu 18.04
**CPU architecture:** x86_64   
**How docker service was installed:**  docker.com repo    

## Command used to create docker container (run/create/compose/screenshot)

docker run -d \
  --name=deluge \
  --net=host \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Europe/Amsterdam \
  -v /var/docks/deluge/config:/config \
  -v /var/downloads:/downloads \
  --restart=always \
  linuxserver/deluge

## Docker logs

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
[cont-init.d] 30-config: exited 0.
[cont-init.d] 99-custom-scripts: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
21:44:49 [WARNING ][deluge.i18n.util           :83  ] IOError when loading translations: [Errno 2] No translation file found for domain: 'deluge'
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
s6-svwait: fatal: supervisor died
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing...
usermod: no changes

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
[cont-init.d] 30-config: exited 0.
[cont-init.d] 99-custom-scripts: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
21:54:47 [WARNING ][deluge.i18n.util           :83  ] IOError when loading translations: [Errno 2] No translation file found for domain: 'deluge'
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
s6-svwait: fatal: supervisor died
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing...
usermod: no changes

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
[cont-init.d] 30-config: exited 0.
[cont-init.d] 99-custom-scripts: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
21:57:33 [WARNING ][deluge.i18n.util           :83  ] IOError when loading translations: [Errno 2] No translation file found for domain: 'deluge'
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
s6-svwait: fatal: supervisor died
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing...
usermod: no changes

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
[cont-init.d] 30-config: exited 0.
[cont-init.d] 99-custom-scripts: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
21:59:32 [WARNING ][deluge.i18n.util           :83  ] IOError when loading translations: [Errno 2] No translation file found for domain: 'deluge'
22:23:24 [ERROR   ][deluge.ui.client           :169 ] RPCError Message Received!
--------------------------------------------------------------------------------
RPCRequest: webapi.set_config({'enable_cors': True})
--------------------------------------------------------------------------------
KeyError
'JSON': Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/deluge/core/rpcserver.py", line 326, in dispatch
    ret = self.factory.methods[method](*args, **kwargs)
  File "/config/plugins/WebAPI-0.4.0-py3.6.egg/webapi/core.py", line 43, in set_config
    self.patch_web_ui()
  File "/config/plugins/WebAPI-0.4.0-py3.6.egg/webapi/core.py", line 59, in patch_web_ui
    cmp_json = component.get('JSON')
  File "/usr/lib/python3/dist-packages/deluge/component.py", line 489, in get
    return _ComponentRegistry.components[name]
KeyError: 'JSON'

--------------------------------------------------------------------------------
22:23:24 [ERROR   ][deluge.ui.web.json_api     :185 ] [Failure instance: Traceback (failure with no frames): <class 'deluge.error.WrappedException'>: 'JSON'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/deluge/core/rpcserver.py", line 326, in dispatch
    ret = self.factory.methods[method](*args, **kwargs)
  File "/config/plugins/WebAPI-0.4.0-py3.6.egg/webapi/core.py", line 43, in set_config
    self.patch_web_ui()
  File "/config/plugins/WebAPI-0.4.0-py3.6.egg/webapi/core.py", line 59, in patch_web_ui
    cmp_json = component.get('JSON')
  File "/usr/lib/python3/dist-packages/deluge/component.py", line 489, in get
    return _ComponentRegistry.components[name]
KeyError: 'JSON'

]
22:23:24 [ERROR   ][deluge.ui.client           :169 ] RPCError Message Received!
--------------------------------------------------------------------------------
RPCRequest: webapi.set_config({'allowed_origin': []})
--------------------------------------------------------------------------------
KeyError
'JSON': Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/deluge/core/rpcserver.py", line 326, in dispatch
    ret = self.factory.methods[method](*args, **kwargs)
  File "/config/plugins/WebAPI-0.4.0-py3.6.egg/webapi/core.py", line 43, in set_config
    self.patch_web_ui()
  File "/config/plugins/WebAPI-0.4.0-py3.6.egg/webapi/core.py", line 59, in patch_web_ui
    cmp_json = component.get('JSON')
  File "/usr/lib/python3/dist-packages/deluge/component.py", line 489, in get
    return _ComponentRegistry.components[name]
KeyError: 'JSON'

--------------------------------------------------------------------------------
22:23:24 [ERROR   ][deluge.ui.web.json_api     :185 ] [Failure instance: Traceback (failure with no frames): <class 'deluge.error.WrappedException'>: 'JSON'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/deluge/core/rpcserver.py", line 326, in dispatch
    ret = self.factory.methods[method](*args, **kwargs)
  File "/config/plugins/WebAPI-0.4.0-py3.6.egg/webapi/core.py", line 43, in set_config
    self.patch_web_ui()
  File "/config/plugins/WebAPI-0.4.0-py3.6.egg/webapi/core.py", line 59, in patch_web_ui
    cmp_json = component.get('JSON')
  File "/usr/lib/python3/dist-packages/deluge/component.py", line 489, in get
    return _ComponentRegistry.components[name]
KeyError: 'JSON'

]
22:23:38 [ERROR   ][deluge.ui.client           :169 ] RPCError Message Received!
--------------------------------------------------------------------------------
RPCRequest: webapi.set_config({'enable_cors': True})
--------------------------------------------------------------------------------
KeyError
'JSON': Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/deluge/core/rpcserver.py", line 326, in dispatch
    ret = self.factory.methods[method](*args, **kwargs)
  File "/config/plugins/WebAPI-0.4.0-py3.6.egg/webapi/core.py", line 43, in set_config
    self.patch_web_ui()
  File "/config/plugins/WebAPI-0.4.0-py3.6.egg/webapi/core.py", line 59, in patch_web_ui
    cmp_json = component.get('JSON')
  File "/usr/lib/python3/dist-packages/deluge/component.py", line 489, in get
    return _ComponentRegistry.components[name]
KeyError: 'JSON'

--------------------------------------------------------------------------------
22:23:38 [ERROR   ][deluge.ui.web.json_api     :185 ] [Failure instance: Traceback (failure with no frames): <class 'deluge.error.WrappedException'>: 'JSON'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/deluge/core/rpcserver.py", line 326, in dispatch
    ret = self.factory.methods[method](*args, **kwargs)
  File "/config/plugins/WebAPI-0.4.0-py3.6.egg/webapi/core.py", line 43, in set_config
    self.patch_web_ui()
  File "/config/plugins/WebAPI-0.4.0-py3.6.egg/webapi/core.py", line 59, in patch_web_ui
    cmp_json = component.get('JSON')
  File "/usr/lib/python3/dist-packages/deluge/component.py", line 489, in get
    return _ComponentRegistry.components[name]
KeyError: 'JSON'

]
22:23:38 [ERROR   ][deluge.ui.client           :169 ] RPCError Message Received!
--------------------------------------------------------------------------------
RPCRequest: webapi.set_config({'allowed_origin': []})
--------------------------------------------------------------------------------
KeyError
'JSON': Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/deluge/core/rpcserver.py", line 326, in dispatch
    ret = self.factory.methods[method](*args, **kwargs)
  File "/config/plugins/WebAPI-0.4.0-py3.6.egg/webapi/core.py", line 43, in set_config
    self.patch_web_ui()
  File "/config/plugins/WebAPI-0.4.0-py3.6.egg/webapi/core.py", line 59, in patch_web_ui
    cmp_json = component.get('JSON')
  File "/usr/lib/python3/dist-packages/deluge/component.py", line 489, in get
    return _ComponentRegistry.components[name]
KeyError: 'JSON'

--------------------------------------------------------------------------------
22:23:38 [ERROR   ][deluge.ui.web.json_api     :185 ] [Failure instance: Traceback (failure with no frames): <class 'deluge.error.WrappedException'>: 'JSON'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/deluge/core/rpcserver.py", line 326, in dispatch
    ret = self.factory.methods[method](*args, **kwargs)
  File "/config/plugins/WebAPI-0.4.0-py3.6.egg/webapi/core.py", line 43, in set_config
    self.patch_web_ui()
  File "/config/plugins/WebAPI-0.4.0-py3.6.egg/webapi/core.py", line 59, in patch_web_ui
    cmp_json = component.get('JSON')
  File "/usr/lib/python3/dist-packages/deluge/component.py", line 489, in get
    return _ComponentRegistry.components[name]
KeyError: 'JSON'

]
22:26:14 [ERROR   ][deluge.ui.client           :169 ] RPCError Message Received!
--------------------------------------------------------------------------------
RPCRequest: webapi.set_config({'allowed_origin': []})
--------------------------------------------------------------------------------
KeyError
'JSON': Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/deluge/core/rpcserver.py", line 326, in dispatch
    ret = self.factory.methods[method](*args, **kwargs)
  File "/config/plugins/WebAPI-0.4.0-py3.6.egg/webapi/core.py", line 43, in set_config
    self.patch_web_ui()
  File "/config/plugins/WebAPI-0.4.0-py3.6.egg/webapi/core.py", line 59, in patch_web_ui
    cmp_json = component.get('JSON')
  File "/usr/lib/python3/dist-packages/deluge/component.py", line 489, in get
    return _ComponentRegistry.components[name]
KeyError: 'JSON'

--------------------------------------------------------------------------------
22:26:14 [ERROR   ][deluge.ui.web.json_api     :185 ] [Failure instance: Traceback (failure with no frames): <class 'deluge.error.WrappedException'>: 'JSON'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/deluge/core/rpcserver.py", line 326, in dispatch
    ret = self.factory.methods[method](*args, **kwargs)
  File "/config/plugins/WebAPI-0.4.0-py3.6.egg/webapi/core.py", line 43, in set_config
    self.patch_web_ui()
  File "/config/plugins/WebAPI-0.4.0-py3.6.egg/webapi/core.py", line 59, in patch_web_ui
    cmp_json = component.get('JSON')
  File "/usr/lib/python3/dist-packages/deluge/component.py", line 489, in get
    return _ComponentRegistry.components[name]
KeyError: 'JSON'

]
22:26:25 [ERROR   ][deluge.ui.client           :169 ] RPCError Message Received!
--------------------------------------------------------------------------------
RPCRequest: webapi.set_config({'allowed_origin': []})
--------------------------------------------------------------------------------
KeyError
'JSON': Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/deluge/core/rpcserver.py", line 326, in dispatch
    ret = self.factory.methods[method](*args, **kwargs)
  File "/config/plugins/WebAPI-0.4.0-py3.6.egg/webapi/core.py", line 43, in set_config
    self.patch_web_ui()
  File "/config/plugins/WebAPI-0.4.0-py3.6.egg/webapi/core.py", line 59, in patch_web_ui
    cmp_json = component.get('JSON')
  File "/usr/lib/python3/dist-packages/deluge/component.py", line 489, in get
    return _ComponentRegistry.components[name]
KeyError: 'JSON'

--------------------------------------------------------------------------------
22:26:25 [ERROR   ][deluge.ui.web.json_api     :185 ] [Failure instance: Traceback (failure with no frames): <class 'deluge.error.WrappedException'>: 'JSON'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/deluge/core/rpcserver.py", line 326, in dispatch
    ret = self.factory.methods[method](*args, **kwargs)
  File "/config/plugins/WebAPI-0.4.0-py3.6.egg/webapi/core.py", line 43, in set_config
    self.patch_web_ui()
  File "/config/plugins/WebAPI-0.4.0-py3.6.egg/webapi/core.py", line 59, in patch_web_ui
    cmp_json = component.get('JSON')
  File "/usr/lib/python3/dist-packages/deluge/component.py", line 489, in get
    return _ComponentRegistry.components[name]
KeyError: 'JSON'

]
22:29:34 [ERROR   ][deluge.ui.client           :169 ] RPCError Message Received!
--------------------------------------------------------------------------------
RPCRequest: webapi.set_config({'allowed_origin': []})
--------------------------------------------------------------------------------
KeyError
'JSON': Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/deluge/core/rpcserver.py", line 326, in dispatch
    ret = self.factory.methods[method](*args, **kwargs)
  File "/config/plugins/WebAPI-0.4.0-py3.6.egg/webapi/core.py", line 43, in set_config
    self.patch_web_ui()
  File "/config/plugins/WebAPI-0.4.0-py3.6.egg/webapi/core.py", line 59, in patch_web_ui
    cmp_json = component.get('JSON')
  File "/usr/lib/python3/dist-packages/deluge/component.py", line 489, in get
    return _ComponentRegistry.components[name]
KeyError: 'JSON'

--------------------------------------------------------------------------------
22:29:34 [ERROR   ][deluge.ui.web.json_api     :185 ] [Failure instance: Traceback (failure with no frames): <class 'deluge.error.WrappedException'>: 'JSON'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/deluge/core/rpcserver.py", line 326, in dispatch
    ret = self.factory.methods[method](*args, **kwargs)
  File "/config/plugins/WebAPI-0.4.0-py3.6.egg/webapi/core.py", line 43, in set_config
    self.patch_web_ui()
  File "/config/plugins/WebAPI-0.4.0-py3.6.egg/webapi/core.py", line 59, in patch_web_ui
    cmp_json = component.get('JSON')
  File "/usr/lib/python3/dist-packages/deluge/component.py", line 489, in get
    return _ComponentRegistry.components[name]
KeyError: 'JSON'

]

**Comment by arjenanker** [comment]
Disabled the WebAPI plugin, which gives a ton of errors for some reason... makes no difference.
